# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjNgx_PB1c6dNpwRxfstxsdeTAHpmkmn
"""

from typing import List
class Solution:
    def isAnagram(self, s: str, t: str) -> bool:
                return((len(s)==len(t)) and (sorted(list(s))==sorted(list(t))))
Sol=Solution()
print(Sol.isAnagram("racecar","carrace"))
print(Sol.isAnagram("jar","jam"))