# -*- coding: utf-8 -*-
"""Neetcode_topKFrequent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjNgx_PB1c6dNpwRxfstxsdeTAHpmkmn
"""

from typing import List

class Solution:
    def topKFrequent(self, nums: List[int], k: int) -> List[int]:
        check_list={}
        for i in nums:
            if i in check_list:
                check_list[i]=check_list[i]+1
            else:
                check_list[i]=1
        key=(list(check_list.keys()))
        val=(list(check_list.values()))
        res=[]
        for i in range(k):
            res.append(key[val.index(max(val))])
            key.pop(val.index(max(val)))
            val.pop(val.index(max(val)))
        return res
Sol=Solution()
print(Sol.topKFrequent( [1,2,2,3,3,3], 2))
print(Sol.topKFrequent([7,7],1))