# -*- coding: utf-8 -*-
"""Neetcode_groupAnagrams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjNgx_PB1c6dNpwRxfstxsdeTAHpmkmn
"""

from typing import List

class Solution:
    def groupAnagrams(self, strs: List[str]) -> List[List[str]]:
        check_list={}
        for i in strs:
            i_adj="".join(sorted(i))
            if i_adj in check_list:
                check_list[i_adj].append(i)
            else:
                check_list[i_adj]=[i]
        return list(check_list.values())
Sol=Solution()
print(Sol.groupAnagrams(["act","pots","tops","cat","stop","hat"]))
print(Sol.groupAnagrams(["act"]))