# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjNgx_PB1c6dNpwRxfstxsdeTAHpmkmn
"""

from typing import List

class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        check_list={}
        for i in range(len(nums)):
            comp=target-nums[i]
            if(comp in check_list):
                return [check_list[comp],i]
            else:
                check_list[nums[i]]=i
Sol=Solution()
print(Sol.twoSum([3,4,5,6],7))
print(Sol.twoSum([4,5,6],10))
print(Sol.twoSum([1,1],2))