# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjNgx_PB1c6dNpwRxfstxsdeTAHpmkmn
"""

from typing import List
class Solution:
    def hasDuplicate(self, nums: List[int]) -> bool:
        return not (len(set(nums))==len(nums))

Solution=Solution()
print(Solution.hasDuplicate([1,2,3,1]))
print(Solution.hasDuplicate([1,2,3,4]))